/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AirfareIndexRouteImport } from './routes/airfare-index'
import { Route as RouteAnalyticsRouteImport } from './routes/route-analytics'
import { Route as TrendsRouteImport } from './routes/trends'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AirfareIndexRoute = AirfareIndexRouteImport.update({
  id: '/airfare-index',
  path: '/airfare-index',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteAnalyticsRoute = RouteAnalyticsRouteImport.update({
  id: '/route-analytics',
  path: '/route-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/airfare-index': typeof AirfareIndexRoute
  '/route-analytics': typeof RouteAnalyticsRoute
  '/trends': typeof TrendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/airfare-index': typeof AirfareIndexRoute
  '/route-analytics': typeof RouteAnalyticsRoute
  '/trends': typeof TrendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/airfare-index': typeof AirfareIndexRoute
  '/route-analytics': typeof RouteAnalyticsRoute
  '/trends': typeof TrendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/airfare-index' | '/route-analytics' | '/trends'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/airfare-index' | '/route-analytics' | '/trends'
  id: '__root__' | '/' | '/airfare-index' | '/route-analytics' | '/trends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AirfareIndexRoute: typeof AirfareIndexRoute
  RouteAnalyticsRoute: typeof RouteAnalyticsRoute
  TrendsRoute: typeof TrendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airfare-index': {
      id: '/airfare-index'
      path: '/airfare-index'
      fullPath: '/airfare-index'
      preLoaderRoute: typeof AirfareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-analytics': {
      id: '/route-analytics'
      path: '/route-analytics'
      fullPath: '/route-analytics'
      preLoaderRoute: typeof RouteAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AirfareIndexRoute: AirfareIndexRoute,
  RouteAnalyticsRoute: RouteAnalyticsRoute,
  TrendsRoute: TrendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
